# Generated by Django 3.0 on 2021-03-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='banner')),
                ('banner', models.ImageField(blank=True, upload_to='banner')),
                ('url', models.URLField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('movie_release_date', models.DateTimeField()),
                ('featured', models.BooleanField(default=False)),
                ('length', models.TimeField()),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Person')),
            ],
        ),
        migrations.DeleteModel(
            name='CourseAPI',
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(related_name='director', to='api.Person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='stars',
            field=models.ManyToManyField(related_name='star', to='api.Person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='writter',
            field=models.ManyToManyField(related_name='writter', to='api.Person'),
        ),
    ]
