# Generated by Django 3.0.8 on 2020-07-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0002_auto_20200721_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[(1, '1080p Movies'), (2, '300Mb Movies'), (3, '720p HEVC Movies'), (4, 'Bollywood Movies'), (5, 'Bollywood Mp3 Songs'), (6, 'Bollywood Video Songs'), (7, 'Dual Audio'), (8, 'English TV Shows'), (9, 'Hindi Dubbed'), (10, 'Hindi TV Shows'), (11, 'Hollywood Movies'), (12, 'Malayalam Movies'), (13, 'Marathi Movies'), (14, 'Mobile Movies'), (15, 'Multi Audio'), (16, 'Pakistani Movies'), (17, 'Pc Games'), (18, 'Pre Release'), (19, 'Punjabi Movies'), (20, 'Single Video Songs'), (21, 'Tamil Movies'), (22, 'Telugu Movies'), (23, 'Trailers'), (24, 'Uncategorized'), (25, 'WEB Series')], default=None, max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
