# Generated by Django 3.0.8 on 2020-07-26 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0006_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
