# Generated by Django 3.0 on 2020-08-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='ssLink',
            field=models.URLField(blank=True),
        ),
    ]
